### ISSUE TITLE
Fjerne notifikasjon

### ISSUE THREAD

**Issue by andrmos** [NicTorgersen/skakkehanopluss-firefox#1]
Hei,
Hadde vært greit å ha muligheten til å velge om man vil vise notifikasjon når artikler er blitt fjernet.
Har du mulighet til å legge inn dette?

Hvis du legger til instruksjoner til hvordan å bygge utvidelsen kan jeg gjerne legge inn en pull request selv.

**Comment by NicTorgersen** [comment]
Hei, @andrmos!

Takk for interessen du viser til dette søte lille prosjektet.

Planen min er å samkjøre dette repoet med chrome-repoet (ettersom WebExtension apiet er såpass standardisert, noe jeg ikke var klar over da jeg opprettet dette som et separat repo) slik at det bare er èn kodebase å forholde seg til. Har flere brukere på chrome og har derfor neglisjert firefox...

Er litt usikker på når jeg egentlig kan ta meg tid til akkurat dette, men i mellomtiden kan du gjerne legge til denne innstillingen! [Har allerede fikset dette i chrome-utvidelsen](https://github.com/NicTorgersen/skakkehanopluss-chrome/commit/c7f3c1e9fd54a69b954dc27ec6601bb2e8177538).

**Comment by NicTorgersen** [comment]
Da ligger nytt repo ute:

https://github.com/NicTorgersen/skakkehanopluss
